project:
  type: website

website:
  title: "Sehaj-notepad"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/sehajsasan
      - icon: twitter
        href: https://twitter.com/sehajsasan
format:
  html:
    theme: cosmo
    css: styles.css



