project:
  type: website

website:
  title: "Sehaj-notepad"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/sehajsasan
      - icon: twitter
        href: https://twitter.com/sehajsasan
  comments: 
    utterances:
      repo: quarto-dev/quarto-web
format:
  html:
    theme: sandstone
    css: styles.css



