project:
  type: website

website:
  title: "Sehaj-notepad"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/sehajsasan
      - icon: twitter
        href: https://twitter.com/sehajsasan
      - icon: linkedin
        href: https://www.linkedin.com/in/sehajdeeep-singh-3a54957a/
  comments: 
    utterances:
      repo: quarto-dev/quarto-web
format:
  html:
    theme: morph
    css: styles.css



